# Specify a base image
FROM node:16-alpine

USER node
RUN mkdir -p /home/node/app
# Setup working directory
WORKDIR /home/node/app

# Copy package.json to working directory
COPY --chown=node:node package*.json ./

# Install package dependency modules
RUN npm install

# Copy source code to working directory
COPY --chown=node:node ./ ./

# Initial process
CMD ["npm","start"]